# Generated by Django 3.0.7 on 2020-06-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200619_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimage',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileimage',
            name='width',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
