# Generated by Django 3.0.7 on 2020-06-27 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20200621_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimage',
            name='height',
            field=models.PositiveSmallIntegerField(default=128, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='fileimage',
            name='width',
            field=models.PositiveSmallIntegerField(default=128, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
